import numpy as np
import pandas as pd

from pathlib import Path
import logging
import sys

from deepchem.utils.typing import RDKitAtom, RDKitBond, RDKitMol
from deepchem.feat.graph_data import GraphData

from deepchem.feat.base_classes import IChemFeaturizer
from deepchem.utils.geometry_utils import compute_pairwise_distances
from deepchem.utils.ichem_parse_utils import parse_multimol2, extract_int_info, extract_atom_info, modify_rdkit_mol
from deepchem.utils.ichem_feature_utils import get_int_atom_type_one_hot, get_atom_symbol_one_hot, get_node_type_one_hot, get_BSA 

# Create a logger with date-time formatting
logger = logging.getLogger('my_logger')
logger.setLevel(logging.ERROR)

console_handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter('%(asctime)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
console_handler.setFormatter(formatter)
logger.addHandler(console_handler)

    
class IPAMapFeaturizer(IChemFeaturizer):
    '''This class is a featurizer for graph convolutional networks for IPA (interaction pseudoatoms) map generated by IChem
    (https://pubmed.ncbi.nlm.nih.gov/29024463/) TIFP (ints) routine.

    Input: 
    
    Int Atom Type: a one-hot-vector of 8 interaction types - CA, CZ, O, OG, N, OD1, NZ, ZN; for detailed descriptions check IChem
    User Guide [3]_ and paper [2]_

    Atom Type: Ligand or Protein Atom
    
    Bond length: Scalar value of bond length in Angstrom.

    References
    ----------
    [1]
    [2]

    Note
    ----
    This class requires RDKit to be installed.
    
    '''
    def __init__(self, edge_cutoff=4, use_atom_symbols=False, use_BSA=False, use_center_atoms=False, use_bond_type=False, use_pseudo=False):

        """
        Parameters
        ----------
        multimol_file_path: Path
            Path object containing filepath to multimol2 file containing pose
        pose_id: str
            Pose_id
        edge_cutoff: float
            Cutoff distance for creating an edge between 2 atoms that come from the same molecule (whether ligand or protein).
            Default to 4A.

        use_atom_symbols: boolean
            Extend node features to include actual atom symbols (in addition to interaction atom symbols) defined by RDkit with
            the default set of '`["C", "N", "O", "F", "P", "S", "Cl", "Br", "I"]`'.

        use_bond_type: boolean
            Extend bond features to explicitly specify covalent ('C') or noncovalent ('NC') bond types
            
        """
        
        self.edge_cutoff = edge_cutoff
        self.use_atom_symbols = use_atom_symbols
        self.use_BSA = use_BSA
        self.use_center_atoms = use_center_atoms
        self.use_bond_type = use_bond_type
        self.use_pseudo = use_pseudo

        self.INT_SYMBOLS = ['CA', 'CZ', 'O', 'OG', 'N', 'OD1', 'NZ', 'ZN']
        
        if not use_center_atoms:
            self.NODE_TYPES = ['L', 'P']            
        else:
            self.NODE_TYPES = ['L', 'P', 'C']

        if use_atom_symbols:
            self.ATOM_TYPES = ["C", "N", "O", "F", "P", "S", "Cl", "Br", "I"]

        if use_bond_type:
            self.BOND_TYPES = ['C', 'NC']
            
    def _get_IPA_map_filepath(self, multimol2_file_path, pose_id):
        ''' Customizable function that returns the file path for interaction pseudo-atom (IPA) map (.mol2) to be featurized
    
            Input:
            -----
                multimol2_file_path: str
                    File path in the format AAAA.mol2 where all redocked/crossdocked poses ending with AAAA (ligand ID) are contained
        
                pose_id: str
                    Full pose id in the format AAAABBBB_i where AAAA: protein ID, BBBB: ligand ID, i: pose ID
            Return:
            ------
                mol2_file_path: Path
                    File path for IPA map to be featurized into a graph
        '''
        
        # Create a temporary dir to store extracted mol2 file
        temp_dir = Path(multimol2_file_path).parent / 'temp'
        temp_dir.mkdir(parents=True, exist_ok=True)
    
        # Parse multimol2 file and extract mol2 file of given pose_id and save it in temp dir
        parse_multimol2(multimol2_file_path, pose_id)
    
        # Define path to the mol2 file in temp dir
        mol2_file_path = temp_dir / (pose_id + ".mol2")
    
        # Check if the file is successfully created
        if mol2_file_path.exists():  
            logger.info("Mol2 file extracted.")
            return mol2_file_path
        else:
            return None
    
    def _parse_IPA_map(self, mol2_file_path):
        ''' Parses and extracts interaction info and atom info out of IPA_map
    
            Variables
            ---------
            int_atom_idx: list
                list of tuples: (int_idx, atm_idx (L), lig_symbol, atm_idx (P), prot_symbol)
                
            lig/prot_dict: dictionary
                {atom_idx: atom_symbol}
    
            atom_info_dict: dictionary
                {atom_idx: (residue, interaction_type)}
    
            bsa_lig/prot_dict: dictionary
                {atom_idx: bsa} for ligand and protein atoms respectively
        '''
    
        pose_id = str(mol2_file_path.name)
        
        # Extract interaction info from mol2 file
        int_atom_idx, lig_dict, prot_dict = extract_int_info(mol2_file_path)
    
        # Extract atom info from mol2 file
        if not self.use_BSA:
            atom_info_dict = extract_atom_info(mol2_file_path, lig_dict, prot_dict, use_BSA=self.use_BSA)
    
            return int_atom_idx, lig_dict, prot_dict, atom_info_dict
        else:
            atom_info_dict, bsa_lig_dict, bsa_prot_dict = extract_atom_info(mol2_file_path, lig_dict, prot_dict, use_BSA=self.use_BSA)
    
            return int_atom_idx, lig_dict, prot_dict, atom_info_dict, bsa_lig_dict, bsa_prot_dict
    
    
    def _modify_rdkit_mol(self, mol2_file_path, int_atom_idx, atom_info_dict, lig_dict, prot_dict, bsa_lig_dict, bsa_prot_dict):
        ''' Modify rdkit mol object for ease of graph generation given interaction and atom information
        '''
        rdkit_mol = modify_rdkit_mol(mol2_file_path, int_atom_idx, atom_info_dict, lig_dict, prot_dict, 
                                    use_atom_symbols=self.use_atom_symbols, use_BSA=self.use_BSA, bsa_lig_dict=bsa_lig_dict, 
                                    bsa_prot_dict = bsa_prot_dict, use_pseudo=self.use_pseudo)
        return rdkit_mol
        
    def _calculate_dist_between_atoms(self, mol: RDKitMol) -> np.ndarray:
        ''' Compute distances between all ligand atoms and all protein atoms
        '''

        try:
            # Conformer object contains 3D coordinates
            conformer = mol.GetConformer(0)
    
            # Define list of coordinates
            atoms_coords = []
    
            for i, atom in enumerate(mol.GetAtoms()):
                pos = conformer.GetAtomPosition(i)
                coord = [pos.x, pos.y, pos.z]
                atoms_coords.append(coord)
            
            dist_mat = compute_pairwise_distances(np.array(atoms_coords), np.array(atoms_coords))

            return dist_mat
            
        except Exception as e:
            logger.error(
                "Failed to calculate distance matrix" 
            )
            logger.error(
                "Exception message: %s", e
            )
            return None
            

    def _prune_nodes(self, dist_mat, lig_dict, prot_dict):
        ''' Calculate distances between all atom pairs and prune distances greater than 6A between P-L 

            Returns
            -------
            valid_nodes: list
                list of node indexes that are valid (less than 6A between P-L)
        '''

        try:
            # Extract lig and prot indices from dictionaries
            lig_idxs = tuple(lig_dict.keys())
            prot_idxs = tuple(prot_dict.keys())
    
            # Initialize lists for lig and prot indices to keep
            lig_idxs_to_keep = []
            prot_idxs_to_keep = []
    
            # Loop over distances and append indices to keep
            for l in lig_idxs:
                for p in prot_idxs:
                    if dist_mat[l][p] < 6:
                        lig_idxs_to_keep.append(l)
                        prot_idxs_to_keep.append(p)
    
            idxs_to_keep = lig_idxs_to_keep + prot_idxs_to_keep

            # Sort it lowest to highest index and keep only unique
            return sorted(set(idxs_to_keep)) 
            
        except Exception as e:
            logger.error(
                "Failed to prune nodes" 
            )
            logger.error(
                "Exception message: %s", e
            )
            return None
            
    def _atom_featurizer(self, atom: RDKitAtom, mol: RDKitMol, idx) -> np.ndarray:

        int_symbol = get_int_atom_type_one_hot(mol, idx, self.INT_SYMBOLS, False)
        node_type = get_node_type_one_hot(atom, self.NODE_TYPES, False)
        
        if (not self.use_atom_symbols) & (not self.use_BSA):
        
            atom_feat = np.concatenate([int_symbol, node_type])
            
            return atom_feat            
        elif (self.use_atom_symbols) & (not self.use_BSA):
            
            atom_symbol = get_atom_symbol_one_hot(mol, idx, self.ATOM_TYPES, True)
            
            atom_feat = np.concatenate([int_symbol, atom_symbol, node_type])

            return atom_feat

        elif (not self.use_atom_symbols) & (self.use_BSA):

            atom_bsa = np.array([get_BSA(mol, idx)])

            atom_feat = np.concatenate([int_symbol, node_type, atom_bsa])

            return atom_feat
        else:

            atom_symbol = get_atom_symbol_one_hot(mol, idx, self.ATOM_TYPES, True)
            atom_bsa = np.array([get_BSA(mol, idx)])
            
            atom_feat = np.concatenate([int_symbol, atom_symbol, node_type, atom_bsa])

            return atom_feat

    def _construct_bond_features(self, src_idxs, dest_idxs, dist_mat):
        ''' Construct bond features given source and destination indices
        '''

        # Initialize feature numpy array
        bond_feat = []

        if not self.use_bond_type:
            for s in src_idxs:
                for d in dest_idxs:
                    bond_feat.append(dist_mat[s][d])

            return  np.expand_dims(bond_feat, axis=1)
            
        else:
            # Unimplented
            return None
        
    def _edge_featurizer(self, dist_mat, idxs_to_keep, int_atom_idx, lig_dict, prot_dict):
        
        ''' Compute edge index and features within the same molecule (protein or ligand).
        '''

        # Calculate edges between the same molecule (L-L, P-P)
        
        # Initialize source and destination indices
        src_idxs, dest_idxs = [], []
        
        # Extract lig and prot indices from dictionaries
        lig_idxs = tuple(lig_dict.keys())
        prot_idxs = tuple(prot_dict.keys())

        # Loop over ligand distances
        for l1 in lig_idxs:
            for l2 in lig_idxs:
                if (dist_mat[l1][l2] < self.cutoff) & (l1 in idxs_to_keep) & (l2 in idxs_to_keep):
                    src_idxs.append(l1)
                    dest_idxs.append(l2) 

        # Loop over protein distances
        for p1 in prot_idxs:
            for p2 in prot_idxs:
                if (dist_mat[p1][p2] < self.cutoff) & (p1 in idxs_to_keep) & (p2 in idxs_to_keep):
                    src_idxs.append(p1)
                    dest_idxs.append(p2) 
                    
        # Calculate interaction edges (L-P)
        for i, lig_idx, _, prot_idx, _ in int_atom_idx:
            if (lig_idx in idxs_to_keep) & (prot_idx in idxs_to_keep):
                src_idxs.append(lig_idx)
                dest_idxs.append(prot_idx)
        
        # Since the graph is undirected, make edges go both ways

        f_src_idxs = src_idxs + dest_idxs # src -> dest
        f_dest_idxs = dest_idxs + src_idxs # dest -> src

        # Calculate edge_features
        edge_features = self._construct_bond_features(mol, f_src_idxs, f_dest_idxs, dist_mat)

        # Modify edge_index by adjusting indices 

        # Create a dictionary of {original_idx: adjusted_idx}
        idx_dict = {}
        for i, original_idx in enumerate(idxs_to_keep):
            idx_dict[str(original_idx)] = str(i)

        # Adjust indices
        f_adj_src_idxs = []
        f_adj_dest_idxs = []
        
        for idx in f_src_idxs:
            f_adj_src_idxs.append(int(idx_dict[str(idx)]))

        for idx in f_dest_idxs:
            f_adj_dest_idxs.append(int(idx_dict[str(idx)]))

        edge_index = np.array([f_adj_src_idxs, f_adj_dest_idxs],
            dtype=int
        )
        
        return edge_index, edge_features

    def _featurize(self, datapoint, **kwargs) -> GraphData:
        """Calculate pocket-ligand graph from iChem generated interaction pseudoatom map

        Parameters
        ----------
        datapoint: tuple
            Datapoint must be tuple of (multimol2_file_path: Path, pose_id: str)
            
        Returns
        -------
        graph: GraphData
            A molecule graph with some features - excluding edges between protein-ligand interaction
        
        """

        logger.info("Preparing to featurize datapoint: %s", datapoint)
        # Create mol2 file from multimol2 filepath and pose_id
        mol2_file_path = self._get_IPA_map_filepath(datapoint[0], datapoint[1])

        # Extract interaction and atom info from mol2 file
        if mol2_file_path is not None:
            if not self.use_BSA:
                int_atom_idx, lig_dict, prot_dict, atom_info_dict = self._parse_IPA_map(mol2_file_path)
                bsa_lig_dict, bsa_prot_dict = None, None
                print("int_atom_idx: ", int_atom_idx)
                print("lig_dict, prot_dict: ", lig_dict, prot_dict)
                print("atom_info_dict: ", atom_info_dict)

            else:
                int_atom_idx, lig_dict, prot_dict, atom_info_dict, bsa_lig_dict, bsa_prot_dict = self._parse_IPA_map(mol2_file_path)

        else:
            # Delete the mol2 file in temp dir
            #mol2_file_path.unlink()
            return None

        # Create rdkit mol object from interaction and atom info
        rdkit_mol = self._modify_rdkit_mol(mol2_file_path, int_atom_idx, atom_info_dict, lig_dict, prot_dict, bsa_lig_dict, bsa_prot_dict) 

        # Delete the mol2 file in temp dir
        #mol2_file_path.unlink()
        
        if rdkit_mol is None:

            # Delete the mol2 file in temp dir
            #mol2_file_path.unlink()
            return None
            
        # Create distance matrix between all atom pairs
        dist_mat = self._calculate_dist_between_atoms(rdkit_mol)

        if dist_mat is None:
            return None
        
        idxs_to_keep = self._prune_nodes(dist_mat, lig_dict, prot_dict)

        # Create node features for valid nodes
        if len(idxs_to_keep) != 0:
            node_features = np.asarray([
                self._atom_featurizer(rdkit_mol.GetAtomWithIdx(i), rdkit_mol, i) for i in idxs_to_keep
            ], dtype=float)
        else:
            return None

        # Create edge indices and edge features for valid nodes
        try:
            edge_index, edge_features = self._edge_featurizer(dist_mat, idxs_to_keep, int_atom_idx, lig_dict, prot_dict)
            graph = GraphData(node_features, edge_index, edge_features)
            
            return graph
            
        except Exception as e:
            logger.error(
                "Failed to create edge_index and edge_features for pose: %s", datapoint[1] 
            )
            logger.error(
                "Exception message: %s", e
            )
            return None