import numpy as np

from deepchem.utils.typing import RDKitAtom, RDKitBond, RDKitMol
from deepchem.feat.graph_data import GraphData

from deepchem.feat.base_classes import MolecularFeaturizer
from deepchem.utils.geometry_utils import compute_pairwise_distances

from deepchem.utils.ichem_feature_utils import is_ligand_one_hot
from deepchem.utils.ichem_feature_utils import get_tripos_atom_type_one_hot

class IPAMapFeaturizer1(MolecularFeaturizer):
    '''This class is a featurizer for graph convolutional networks for IPA (interaction pseudoatoms) map generated by IChem
    (https://pubmed.ncbi.nlm.nih.gov/29024463/) TIFP routine.

    (Description) - version 1

    Default node representations are constructed by concatenating the following atom features
    
    Atom Type: a one-hot-vector of 8 interaction types - CA, CZ, O, OG, N, OD1, NZ, ZN; for detailed descriptions check IChem
    User Guide [3]_ and paper [2]_

    Default edge representations are constructed by concatenating the following edge features
    
    Bond length: Scalar value of bond length in Angstrom.

    Edge creation

    References
    ----------
    [1]
    [2]

    Note
    ----
    This class requires RDKit to be installed.
    
    '''
    def __init__(self):

        self.SYMBOLS = [
            'CA', 'CZ', 'O', 'OG', 'N', 'OD1', 'NZ', 'ZN' 
        ]

        self.TYPES = [ 'L', 'P' ]
        
    def _atom_featurizer(self, atom: RDKitAtom, mol: RDKitMol, idx) -> np.ndarray:

        atom_symbol = get_tripos_atom_type_one_hot(mol, idx, self.SYMBOLS, False)
        
        atom_type = is_ligand_one_hot(atom, self.TYPES, False)
        
        '''
        Optional configurations
        -----------------------
        formal_charge = get_atom_formal_charge_one_hot(
        atom, include_unknown_set=False)
        degree = get_atom_total_degree_one_hot(atom, list(range(11)), False)
        exp_valence = get_atom_explicit_valence_one_hot(atom, list(range(7)),
                                                        False)
        imp_valence = get_atom_implicit_valence_one_hot(atom, list(range(6)),
                                                        False)
        aromaticity = get_atom_is_in_aromatic_one_hot(atom)
        '''
        atom_feat = np.concatenate([atom_symbol, atom_type])
        
        return atom_feat

    def _edge_featurizer(self, mol: RDKitMol) -> np.ndarray:
        
        ''' Compute edge index and features within the same molecule (protein or ligand).
        '''

        # Initialize arrays to store coordinates for both ligand and protein atoms
        lig_atoms_coords = []
        prot_atoms_coords = []

        # Conformer object contains 3D coordinates
        conformer = mol.GetConformer(0)
        
        for i, atom in enumerate(mol.GetAtoms()):
            if atom.GetProp('Residue')[2] == 'L':
                pos = conformer.GetAtomPosition(i)
                coord = [pos.x, pos.y, pos.z]
                lig_atoms_coords.append(coord)
            elif atom.GetProp('Residue')[2] == 'P':
                pos = conformer.GetAtomPosition(i)
                coord = [pos.x, pos.y, pos.z]
                prot_atoms_coords.append(coord)

        lig_dist_mat = compute_pairwise_distances(np.array(lig_atoms_coords), np.array(lig_atoms_coords))
        prot_dist_mat = compute_pairwise_distances(np.array(prot_atoms_coords), np.array(prot_atoms_coords))

        # Loop through matrix and get edge_index and edge_features for both protein and ligand atoms

        src_idxs = []
        dest_idxs = []
        dists = []
        
        # start from ligand atom index of 1 (how mol2 file should start)
        for i in range(lig_dist_mat.shape[0]):
            for j in range(i+1, lig_dist_mat.shape[0]):
                if (lig_dist_mat[i, j] < 4):
                    src_idxs.append(i)
                    dest_idxs.append(j)
                    dists.append(lig_dist_mat[i][j])

        # protein atom indexes start after ligand
        idx_begin = lig_dist_mat.shape[0]
        for i in range(prot_dist_mat.shape[0]):
            for j in range(i+1, prot_dist_mat.shape[0]):
                if (prot_dist_mat[i, j] < 4):
                    src_idxs.append(idx_begin + i)
                    dest_idxs.append(idx_begin + j)
                    dists.append(prot_dist_mat[i][j])

        return np.array([src_idxs, dest_idxs], dtype=int), np.array(dists, dtype=float)

    def _featurize(self, datapoint: RDKitMol, **kwargs) -> GraphData:
        """Calculate molecule graph features from RDKit mol object.

        Parameters
        ----------
        mol: rdkit.Chem.rdchem.Mol
            RDKit mol object.

        Returns
        -------
        graph: GraphData
            A molecule graph with some features - excluding edges between protein-ligand interaction

        """
        if 'mol' in kwargs:
            datapoint = kwargs.get("mol")
            raise DeprecationWarning(
                'Mol is being phased out as a parameter, please pass "datapoint" instead.'
            )

        node_features = np.asarray([
            self._atom_featurizer(atom, datapoint, i) for i, atom in enumerate(datapoint.GetAtoms())
        ],
                                   dtype=float)
        edge_index, edge_features = self._edge_featurizer(datapoint)
        graph = GraphData(node_features, edge_index, edge_features)
        return graph
