import numpy as np

from deepchem.utils.typing import RDKitAtom, RDKitBond, RDKitMol
from deepchem.feat.graph_data import GraphData

from deepchem.feat.base_classes import MolecularFeaturizer
from deepchem.utils.geometry_utils import compute_pairwise_distances

from deepchem.utils.ichem_feature_utils import get_int_atom_type_one_hot, get_atom_symbol_one_hot, get_node_type_one_hot, get_BSA
    
class IPAMapFeaturizer(MolecularFeaturizer):
    '''This class is a featurizer for graph convolutional networks for IPA (interaction pseudoatoms) map generated by IChem
    (https://pubmed.ncbi.nlm.nih.gov/29024463/) TIFP routine.

    (Description) - version 1 takes IChem defined interaction atom type + ligand/protein atom type as node features and create edges 
    between interacting protein-ligand atoms and atoms of the same molecule if the distance between them is less than 4A
    
    Int Atom Type: a one-hot-vector of 8 interaction types - CA, CZ, O, OG, N, OD1, NZ, ZN; for detailed descriptions check IChem
    User Guide [3]_ and paper [2]_

    Atom Type: Ligand or Protein Atom
    
    Bond length: Scalar value of bond length in Angstrom.

    References
    ----------
    [1]
    [2]

    Note
    ----
    This class requires RDKit to be installed.
    
    '''
    def __init__(self, edge_cutoff=4, use_atom_symbols=False, use_BSA=False, use_center_atoms=False, use_bond_type=False):

        """
        Parameters
        ----------
        edge_cutoff: float
            Cutoff distance for creating an edge between 2 atoms that come from the same molecule (whether ligand or protein).
            Default to 4A.

        use_atom_symbols: boolean
            Extend node features to include actual atom symbols (in addition to interaction atom symbols) defined by RDkit with
            the default set of '`["C", "N", "O", "F", "P", "S", "Cl", "Br", "I"]`'.
            
        """
        
        self.edge_cutoff = edge_cutoff
        self.use_atom_symbols = use_atom_symbols
        self.use_BSA = use_BSA
        self.use_center_atoms = use_center_atoms
        self.use_bond_type = use_bond_type

        self.INT_SYMBOLS = ['CA', 'CZ', 'O', 'OG', 'N', 'OD1', 'NZ', 'ZN']
        
        if not use_center_atoms:
            self.NODE_TYPES = ['L', 'P']            
        else:
            self.NODE_TYPES = ['L', 'P', 'C']

        if use_atom_symbols:
            self.ATOM_TYPES = ["C", "N", "O", "F", "P", "S", "Cl", "Br", "I"]

    def _calculate_dist_between_atoms(self, mol: RDKitMol) -> np.ndarray:
        ''' Compute distances between all ligand atoms and all protein atoms
        '''
        
        # Conformer object contains 3D coordinates
        conformer = mol.GetConformer(0)

        # Calculate distances between L-L and P-P
        if not self.use_center_atoms:
            
            # Initialize arrays to store coordinates for both ligand and protein atoms
            lig_atoms_coords = []
            prot_atoms_coords = []
        
            for i, atom in enumerate(mol.GetAtoms()):
                if atom.GetProp('Residue')[2] == 'L':
                    pos = conformer.GetAtomPosition(i)
                    coord = [pos.x, pos.y, pos.z]
                    lig_atoms_coords.append(coord)
                elif atom.GetProp('Residue')[2] == 'P':
                    pos = conformer.GetAtomPosition(i)
                    coord = [pos.x, pos.y, pos.z]
                    prot_atoms_coords.append(coord)
        
            lig_dist_mat = compute_pairwise_distances(np.array(lig_atoms_coords), np.array(lig_atoms_coords))
            prot_dist_mat = compute_pairwise_distances(np.array(prot_atoms_coords), np.array(prot_atoms_coords))
        
            return lig_dist_mat, prot_dist_mat
            
        else:
            '''Unimplemented for using center atoms
            '''
            return None
        
    def _atom_featurizer(self, atom: RDKitAtom, mol: RDKitMol, idx) -> np.ndarray:

        int_symbol = get_int_atom_type_one_hot(mol, idx, self.INT_SYMBOLS, False)
        node_type = get_node_type_one_hot(atom, self.NODE_TYPES, False)
        
        if (not self.use_atom_symbols) & (not self.use_BSA):
        
            atom_feat = np.concatenate([int_symbol, node_type])
            
            return atom_feat            
        elif (self.use_atom_symbols) & (not self.use_BSA):
            
            atom_symbol = get_atom_symbol_one_hot(mol, idx, self.ATOM_TYPES, True)
            
            atom_feat = np.concatenate([int_symbol, atom_symbol, node_type])

            return atom_feat
        else:

            atom_symbol = get_atom_symbol_one_hot(mol, idx, self.ATOM_TYPES, True)
            atom_bsa = np.array([get_BSA(mol, idx)])
            
            atom_feat = np.concatenate([int_symbol, atom_symbol, node_type, atom_bsa])

            return atom_feat

    def _edge_featurizer(self, mol: RDKitMol) -> np.ndarray:
        
        ''' Compute edge index and features within the same molecule (protein or ligand).
        !!! Still need to implement adding covalent-noncovalent one-hot
        '''

        if not self.use_center_atoms:
                
            # Compute matrix 
            lig_dist_mat, prot_dist_mat = self._calculate_dist_between_atoms(mol)
            
            # Loop through matrix and get edge_index and edge_features for both protein and ligand atoms
    
            src_idxs = []
            dest_idxs = []
            dists = []
            
            # start from ligand atom index of 1 (how mol2 file should start)
            for i in range(lig_dist_mat.shape[0]):
                for j in range(lig_dist_mat.shape[0]):
                    if (lig_dist_mat[i, j] < self.edge_cutoff) and (i != j):
                        src_idxs.append(i)
                        dest_idxs.append(j)
                        dists.append(lig_dist_mat[i][j])
    
            # protein atom indexes start after ligand
            idx_begin = lig_dist_mat.shape[0]
            for i in range(prot_dist_mat.shape[0]):
                for j in range(prot_dist_mat.shape[0]):
                    if (prot_dist_mat[i, j] < self.edge_cutoff) and (i != j):
                        src_idxs.append(idx_begin + i)
                        dest_idxs.append(idx_begin + j)
                        dists.append(prot_dist_mat[i][j])

            print(src_idxs)
            print(dest_idxs)
    
            return np.array([src_idxs, dest_idxs], dtype=int), np.expand_dims(dists, axis=1)
            
        else:
            ''' Unimplemented
            '''
            return

    def _featurize(self, datapoint: RDKitMol, **kwargs) -> GraphData:
        """Calculate molecule graph features from RDKit mol object.

        Parameters
        ----------
        mol: rdkit.Chem.rdchem.Mol
            RDKit mol object.

        Returns
        -------
        graph: GraphData
            A molecule graph with some features - excluding edges between protein-ligand interaction

        """
        if 'mol' in kwargs:
            datapoint = kwargs.get("mol")
            raise DeprecationWarning(
                'Mol is being phased out as a parameter, please pass "datapoint" instead.'
            )

        node_features = np.asarray([
            self._atom_featurizer(atom, datapoint, i) for i, atom in enumerate(datapoint.GetAtoms())
        ],
                                   dtype=float)
        edge_index, edge_features = self._edge_featurizer(datapoint)
        graph = GraphData(node_features, edge_index, edge_features)
        return graph