import numpy as np

from deepchem.utils.typing import RDKitAtom, RDKitBond, RDKitMol
from deepchem.feat.graph_data import GraphData

from deepchem.feat.base_classes import UserDefinedFeaturizer
from deepchem.utils.molecule_feature_utils import one_hot_encode

class IPAMapFeaturizer1(Featurizer):
    '''This class is a featurizer for graph convolutional networks for IPA (interaction pseudoatoms) map generated by IChem
    (https://pubmed.ncbi.nlm.nih.gov/29024463/) TIFP routine.

    (Description) - version 1

    Default node representations are constructed by concatenating the following atom features
    
    Atom Type: a one-hot-vector of 8 interaction types - CA, CZ, O, OG, N, OD1, NZ, ZN; for detailed descriptions check IChem
    User Guide [3]_ and paper [2]_

    Default edge representations are constructed by concatenating the following edge features
    
    Bond length: Scalar value of bond length in Angstrom.

    Edge creation

    References
    ----------
    [1]
    [2]

    Note
    ----
    This class requires RDKit to be installed.
    
    '''

