import numpy as np

from deepchem.utils.typing import RDKitAtom, RDKitBond, RDKitMol
from deepchem.feat.graph_data import GraphData

from deepchem.feat.base_classes import UserDefinedFeaturizer
from deepchem.utils.molecule_feature_utils import get_atom_type_one_hot
from deepchem.utils.ichem_feature_utils import is_ligand_one_hot

class IPAMapFeaturizer1(Featurizer):
    '''This class is a featurizer for graph convolutional networks for IPA (interaction pseudoatoms) map generated by IChem
    (https://pubmed.ncbi.nlm.nih.gov/29024463/) TIFP routine.

    (Description) - version 1

    Default node representations are constructed by concatenating the following atom features
    
    Atom Type: a one-hot-vector of 8 interaction types - CA, CZ, O, OG, N, OD1, NZ, ZN; for detailed descriptions check IChem
    User Guide [3]_ and paper [2]_

    Default edge representations are constructed by concatenating the following edge features
    
    Bond length: Scalar value of bond length in Angstrom.

    Edge creation

    References
    ----------
    [1]
    [2]

    Note
    ----
    This class requires RDKit to be installed.
    
    '''
    def __init__(self):

        self.SYMBOLS = [
            'CA', 'CZ', 'O', 'OG', 'N', 'OD1', 'NZ', 'ZN' 
        ]

        self.TYPES = [ 'L', 'P' ]
        
    def _atom_featurizer(self, atom: RDKitAtom) -> np.ndarray:

        atom_symbol = get_atom_type_one_hot(atom, self.SYMBOLS, False)
        
        atom_type = is_ligand_one_hot(atom, self.TYPES, False)
        
        '''
        Optional configurations
        -----------------------
        formal_charge = get_atom_formal_charge_one_hot(
        atom, include_unknown_set=False)
        degree = get_atom_total_degree_one_hot(atom, list(range(11)), False)
        exp_valence = get_atom_explicit_valence_one_hot(atom, list(range(7)),
                                                        False)
        imp_valence = get_atom_implicit_valence_one_hot(atom, list(range(6)),
                                                        False)
        armoticity = get_atom_is_in_aromatic_one_hot(atom)
        '''
        atom_feat = np.concatenate([atom_symbol, atom_type])
        
        return atom_feat

    def _edge_features(self, mol: RDKitMol) -> np.ndarray:
        